language: node_js
node_js:
    - "6"
    - "6.1"
    - "6.2"
branches:
  only:
    # add your branch here to test it, for now it will test the develop branch.
    - develop
script:
  npm test
notifications:
  email:
    recipients:
      # add your email here for CI updates.
